version: 2
jobs:
  build:
    environment:
      APP_VERSION_NUM: 2.0.0
    working_directory: /app
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run:
          name: Running tests and deploy
          command: |
              dotnet pack -c release --include-symbols -o ${PWD}/artifacts/ /p:Version="${APP_VERSION_NUM}.${CIRCLE_BUILD_NUM}"
              dotnet nuget push "artifacts/Bekk.Pact.Common.${APP_VERSION_NUM}.${CIRCLE_BUILD_NUM}.nupkg" -k ${MYGET_APIKEY} -s https://www.myget.org/F/bekk-intern/api/v2/package
              dotnet nuget push "artifacts/Bekk.Pact.Consumer.${APP_VERSION_NUM}.${CIRCLE_BUILD_NUM}.nupkg" -k ${MYGET_APIKEY} -s https://www.myget.org/F/bekk-intern/api/v2/package
              dotnet nuget push "artifacts/Bekk.Pact.Provider.${APP_VERSION_NUM}.${CIRCLE_BUILD_NUM}.nupkg" -k ${MYGET_APIKEY} -s https://www.myget.org/F/bekk-intern/api/v2/package
              dotnet nuget push "artifacts/Bekk.Pact.Provider.Web.${APP_VERSION_NUM}.${CIRCLE_BUILD_NUM}.nupkg" -k ${MYGET_APIKEY} -s https://www.myget.org/F/bekk-intern/api/v2/package
              dotnet nuget push "artifacts/Bekk.Pact.Common.${APP_VERSION_NUM}.${CIRCLE_BUILD_NUM}.symbols.nupkg" -k ${MYGET_APIKEY} -s https://www.myget.org/F/bekk-intern/api/v2/package
              dotnet nuget push "artifacts/Bekk.Pact.Consumer.${APP_VERSION_NUM}.${CIRCLE_BUILD_NUM}.symbols.nupkg" -k ${MYGET_APIKEY} -s https://www.myget.org/F/bekk-intern/api/v2/package
              dotnet nuget push "artifacts/Bekk.Pact.Provider.${APP_VERSION_NUM}.${CIRCLE_BUILD_NUM}.symbols.nupkg" -k ${MYGET_APIKEY} -s https://www.myget.org/F/bekk-intern/api/v2/package
              dotnet nuget push "artifacts/Bekk.Pact.Provider.Web.${APP_VERSION_NUM}.${CIRCLE_BUILD_NUM}.symbols.nupkg" -k ${MYGET_APIKEY} -s https://www.myget.org/F/bekk-intern/api/v2/package

           